# -*- coding: UTF-8 -*-
# Copyright 2015 Mahmoud Mamdouh
# License: BSD (see file COPYING for details)


from __future__ import unicode_literals
__author__ = 'drx'

def populate(p):
    p.city("El-Marg","")
    p.city("Al Salam","")
    p.city("Ain Shams","")
    p.city("Al-Matariyyah","")
    p.city("Al Zeitoun","")
    p.city("Haddaq Al Qubbah","")
    p.city("Al Nuzhah","")
    p.city("Misr Al Jadidah","")
    p.city("Al Waili","")
    p.city("Al Zawiyah Al Hamra","")
    p.city("Al Sharabiyah","")
    p.city("Al Sajil","")
    p.city("Shobra","")
    p.city("Rud Al Faraj","")
    p.city("Bulaq","")
    p.city("Al Azbakeya","")
    p.city("Manshiyat Naser","")
    p.city("Mokattam","")
    p.city("Madinat Nasr","")
    p.city("Qasr al Nil","")
    p.city("Al Zamalek","")
    p.city("Abdin","")
    p.city("Al Muski","")
    p.city("Bab Al-Shaariyah","")
    p.city("Al Azhar","")
    p.city("Al Jamaliyah","")
    p.city("Al-Darb al Ahmar","")
    p.city("Al Sayidah Zaynab","")
    p.city("Misr Al Qadimah","")
    p.city("Al Khalifa","")
    p.city("Al Basatin","")
    p.city("Maadi","")
    p.city("Turah","")
    p.city("15 May","")
    p.city("Helwan","")
    p.city("Al-Tabin","")
    p.city("Qahirah al Jadidah","")
    p.city("Al Shuruq","")
    p.city("Badr","")
    p.city("Others","")